### ISSUE TITLE
Support Zap logging

### ISSUE THREAD

**Issue by negz** [uber-common/bark#6]
https://github.com/uber-go/zap/commit/1a01bcb79368b1f2113783d7d146742e264750a7

Zap's support for Bark was removed in the above commit in favour of Bark supporting Zap internally. Is there still a plan to add it here?

**Comment by akshayjshah** [comment]
Yes! Sorry for the long, long delay in responding to this - I didn't realize that this repo had been basically abandoned.

**Comment by abhinav** [comment]
Added in #12. Thanks @jkanywhere.
